config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'groups#index'
  devise_for :users

  resources :groups do
    get 'adduser'
    get 'people'
    resources :candidates do
    end
    resources :articles do
    end
    resources :events do
    end
  end
  resources :comments

  # get "/groups/:group_id/people", to: "groups#people", as: "groups"
  get "/groups/:group_id/enters/:id", to: "enters#create", as: "enters"
  delete "/groups/:group_id/enters/:id", to: "enters#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :comments, as: :object
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
end

app/models/enter.rb
class Enter < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :comments, as: :object
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :user
  has_many :articles
  has_many :enters
  has_many :events
  has_many :candidates
  has_many :users, through: :enters
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments

  has_many :groups
  has_many :articles
  has_many :events
  has_many :enters
  has_many :candidates
  has_one_attached :avatar
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, exist: [:show]
  before_action :article, only: [:edit]

  def new
    @article = group.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if article.save
      redirect_to group_path(group.id)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    article.update(article_params)
    redirect_to root_path
  end

  def destroy
    article.destroy
    redirect_to root_path
  end

  def show
    @comments = article.comments
  end

  private

  def article_params
    params.require(:article).permit(:user_id, :title, :body, :group_id)
  end

  def group
    @group ||= Group.find(params[:group_id])
  end

  def article
    @article ||= group.articles.find(params[:id]) if group
  end
end

app/controllers/candidates_controller.rb
# frozen_string_literal: true

class CandidatesController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @candidate = Candidate.create(candidate_params)
    redirect_to group_path(@group)
  end

  private

  def candidate_params
    params.require(:candidate).permit(:name, :group_id)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      redirect_back(fallback_location: root_path)
    else
      # помилку
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :object_id, :object_type, :text)
  end
end

app/controllers/enters_controller.rb
# frozen_string_literal: true

class EntersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group
  before_action :set_enter, only: [:destroy]

  def create
    if $flag == false
      @enter = Enter.create(user_id: current_user.id, group_id: @group.id, permission: true)
      redirect_to group_path(@enter.group_id) if @enter.save
    else
      @candidate = Candidate.last
      @user = User.where(nickname: @candidate.name).last
      @enter = Enter.create(user_id: @user.id, group_id: @group.id, permission: true)
      redirect_to group_path(@enter.group_id)
    end
  end

  def destroy
    @enter.destroy
    redirect_to root_path
  end

  private

  def enter_params
    params.require(:enter).permit(:user_id, :group_id, :permission)
  end

  def set_enter
    @enter = Enter.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_group
  def new
    @event = Event.new
  end

  def create
    params[:event][:group_id] = @group.id
    params[:event][:user_id] = current_user.id
    @event = Event.create(event_params)
    if @event.save
      redirect_to group_path(@group.id)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    @event.update(event_params)
    redirect_to root_path
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  def show
    @event = Event.find(params[:id])
    @comments = @event.comments
  end

  private

  def event_params
    params.require(:event).permit(:user_id, :evname, :day, :group_id, :context)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!, exist: %i[index show]
  before_action :group, only: %i[edit]

  def index
    $flag = false
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if group.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def adduser
    $flag = true
    @candidate = group.candidates.build

    # @user = User.where(nickname: @candidate.name)
    # params[:enter][:user_id] = @user
    # params[:enter][:group_id] = @group.id
    # params[:enter][:permission] = true
    # @enter = Enter.create(enter_params)
    #       redirect_to group_path(@group.id)
  end

  def edit; end

  def update
    group.update(group_params)
    redirect_to group_path(group)
  end

  def destroy
    group.destroy
    redirect_to root_path
  end

  def show
    @enter = group.enters.find_by(user: current_user)

    @autor = group.user
    @articles = group.articles
    @events = group.events
  end

  def people
    @users = group.users
  end

  private

  def group
    @group ||= Group.find_by(id: params[:id]) || Group.find(params[:group_id])
  end

  def group_params
    params.require(:group).permit(:name, :context, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%=f.hidden_field :group_id%>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control' %>

</div>



<div class="form-group">
<%= f.submit 'Зберегти', class: "btn btn-primary active btn-lg" %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>

app/views/articles/new.html.erb
 <%= form_for @article, url:group_articles_path do |f| %>

<%= render 'articles/form',f:f%>
<% end %>

app/views/articles/show.html.erb
<!-- <p><%= link_to @group.name, group_path(@group.id)%></p>  -->
<a style="margin-top: 20px;" class="btn btn-info" href="/groups/<%= @group.id%>" role="button">Redirect in <%=@group.name%></a>
<h1 style="text-align: center;"><%= @article.title %></h1>
<div class="container" style="text-align: justify;">
	<%= @article.body %>

	<%=render @comments%>
</div>
<br/>
<hr>
<%= render "comments/form", object:@article%>

app/views/candidates/_form.html.erb
<%=f.hidden_field :group_id%>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>


<div class="form-group">
<%= f.submit 'Зберегти', class: "btn btn-primary active btn-lg" %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
	<table style="width: 100%;">
	<tr style="width: 50%;">
		<td>
<%= image_tag(comment.user.avatar, width: 50, height: 50) if comment.user.avatar.attached? %>

<%= comment.user.nickname%>
</td>
<td style="width: 50%; text-align: right;">
Create at: <%= comment.created_at %>
</td>
</tr>
	</table>
<p style="padding-top: 10px; padding-left: 55px; padding-right: 55px;"><%=comment.text%></p>
</div>

app/views/comments/_form.html.erb
<div style="text-align: center;">
<%= form_for :comment, url: comments_path() do |f| %>
  <%= f.hidden_field :object_id,value: object.id %>
  <%= f.hidden_field :object_type,value: object.class.name%>
  <%= f.text_area :text %><br>
  <%= f.submit :comment%>
<% end %>
</div>

app/views/events/_form.html.erb
<div class="form-group">
  <%= f.label :evname %>
  <%= f.text_field :evname, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :day %>
  <%= f.datetime_select :day, class: 'form-control' %>
 
</div>



<div class="form-group">
<%= f.submit 'Зберегти', class: "btn btn-primary active btn-lg" %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>

app/views/events/new.html.erb
 <%= form_for @event, url:group_events_path do |f| %>
	<%= render 'events/form',f:f%>
<% end %>

app/views/events/show.html.erb
<a style="margin-top: 20px;" class="btn btn-info" href="/groups/<%= @group.id%>" role="button">Redirect in <%=@group.name%></a><br/>
<h3 style="text-align: center; color: #424874;"><%= @event.evname%></h3>
<table style="width: 100%;">
	<tr>
		<td style="width: 50%;">
			<p style=" color: #424874;"><%= @event.context%></p>
		</td>
		<td style="width: 50%; text-align: right; color: #424874;">
			<h4>Date : <%= @event.day.to_date.strftime('%d %B, %Y') %></h4>
		</td>
	</tr>
</table>
<%=render @comments%>
<br/>
<hr>
<%= render "comments/form", object:@event%>

app/views/groups/_add.html.erb
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.submit 'Зберегти', class: "btn btn-primary active btn-lg" %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>
<%end%>

app/views/groups/_elem.html.erb
<% @enter =  Enter.where(user_id: current_user.id, group_id: group.id).first %>
<div class="container">
	<table style="width: 100%;">
		<tr style="width: 100%">
			<td style="width: 25%; text-align: center;"><h5 style="text-align: center; text-decoration: none; color: #000;"><%=link_to group.name, group_path(group.id) %></h5></td>
			<td style="width: 50%; text-align: center;">Created group in <%= group.created_at.to_date.strftime('%d %B, %Y') %></td>
				<% if current_user.id == group.user_id %>
					<td style="width: 25%; text-align: center;">You autor</td>
				 <% elsif @enter == nil%>
					<td style="width: 25%; text-align: center;"><%= link_to enters_path(group.id, 0) do %>Enter Group <%end%></td>
				<%else%>
					<td style="width: 25%; text-align: center;">
					<%= link_to enters_path(group.id, @enter), method: :delete do %>Exit with Group <%end%>
				</td>
				<%end%>
			
		</tr>
	</table>
</div>

app/views/groups/adduser.html.erb
<%= form_for @candidate, url:group_candidates_path(@group.id) do |f| %>
<%= render 'candidates/form', f:f%>
<%end%>

app/views/groups/index.html.erb
<% @groups.each do |group|%>
<%=render 'groups/elem', group:group%>
<%end%>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>


<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :context %>
  <%= f.text_area :context, class: 'form-control' %>
 
</div>



<div class="form-group">
<%= f.submit 'Зберегти', class: "btn btn-primary active btn-lg" %>
<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>
<%end%>

app/views/groups/people.html.erb
<%= link_to group_path(@group), class:"btn btn-info", style:"margin-top: 20px;" do %>Redirect in <%=@group.name%><%end%>
<div class="box">

	<h1 style="color: #424874; text-align: center;"> People group</h1>
	<div class="row">
		<%= render @group.users%>

	</div>
	<p style="color: brown;text-align: center;">Autor :<br/>
		<%= render @group.user%>
<br/></p>
</div>

app/views/groups/show.html.erb
<!-- <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Library</a></li>
    <li class="breadcrumb-item active" aria-current="page">Data</li>
  </ol>
</nav> -->
<h1 style="text-align: center;"><%= @group.name%></h1>
<table style="width: 100%;">
	<tr>
		<td style="width: 30%;">
			<p style="color: #424874;">Autor: <%= @group.user.nickname %><br></p>
		</td>
		<td style="width: 30%; text-align: center;">
			<a class="btn btn-info" href="/groups/<%= @group.id%>/people" role="button">Count people :<%= Enter.where(group_id: @group.id).count + 1%></a>
		</td>
		<td style="width: 30%; text-align: right; color: #424874;">
			<b style='text-align: right;'>Group created <%= @group.created_at %></b>
		</td>
	<tr>
</table>
<table style="width: 100%;">
		<tr>
			<td style="text-align: left; width: 70%">
			<h3><%= @group.context %></h3>
			</td>
			<td style="text-align: right;">
			<%if @articles.count > 0%>
				<h3 style="text-align: center;">Article group</h3>
				<% @articles.each do |article|%>
					<li><h4 style="text-align: left; text-decoration: none; color: #000;"><%= link_to article.title, group_article_path(@group.id, article) %></h4></li>
				<%end%>
			<%end%>
			<%if @events.count > 0%>
				<h3 style="text-align: center;">Event group</h3>
				<% @events.each do |event|%>
					<li><h4 style="text-align: left; text-decoration: none; color: #000;"><%= link_to event.evname, group_event_path(@group.id, event) %> : <%= event.day.to_date.strftime('%d %B, %Y') %> </h4></li> 
				<%end%>
			<%end%>
			</td>
		</tr>
</table>




<% if current_user.id == @group.user_id %>

<%= link_to group_adduser_path(@group.id) do %>
          <button type="button" class="btn btn-outline-dark">Add user to group</button>
		<%end%>
		<%= link_to new_group_article_path(@group) do %>
          <button type="button" class="btn btn-outline-dark">Add artickes</button>
		<%end%>
		<%= link_to new_group_event_path(@group) do %>
          <button type="button" class="btn btn-outline-dark">Add events</button>
		<%end%>
 <%end%>