config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'groups#index'
  devise_for :users

  resources :groups do
    get 'adduser'
    get 'people'
    resources :candidates do
    end
    resources :articles do
    end
    resources :events do
    end
  end
  resources :comments

  # get "/groups/:group_id/people", to: "groups#people", as: "groups"
  get "/groups/:group_id/enters/:id", to: "enters#create", as: "enters"
  delete "/groups/:group_id/enters/:id", to: "enters#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :comments, as: :object
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
end

app/models/enter.rb
class Enter < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :comments, as: :object
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :user
  has_many :articles
  has_many :enters
  has_many :events
  has_many :candidates
  has_many :users, through: :enters
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments

  has_many :groups
  has_many :articles
  has_many :events
  has_many :enters
  has_many :candidates
  has_one_attached :avatar
end

app/controllers/enters_controller.rb
# frozen_string_literal: true

class EntersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group
  before_action :set_enter, only: [:destroy]

  def create
    if $flag == false
      @enter = Enter.create(user_id: current_user.id, group_id: @group.id, permission: true)
      redirect_to group_path(@enter.group_id) if @enter.save
    else
      @candidate = Candidate.last
      @user = User.where(nickname: @candidate.name).last
      @enter = Enter.create(user_id: @user.id, group_id: @group.id, permission: true)
      redirect_to group_path(@enter.group_id)
    end
  end

  def destroy
    @enter.destroy
    redirect_to root_path
  end

  private

  def enter_params
    params.require(:enter).permit(:user_id, :group_id, :permission)
  end

  def set_enter
    @enter = Enter.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_group
  def new
    @event = Event.new
  end

  def create
    params[:event][:group_id] = @group.id
    params[:event][:user_id] = current_user.id
    @event = Event.create(event_params)
    if @event.save
      redirect_to group_path(@group.id)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    @event.update(event_params)
    redirect_to root_path
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  def show
    @event = Event.find(params[:id])
    @comments = @event.comments
  end

  private

  def event_params
    params.require(:event).permit(:user_id, :evname, :day, :group_id, :context)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!, exist: %i[index show]
  before_action :group, only: %i[edit]

  def index
    $flag = false
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if group.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def adduser
    $flag = true
    @candidate = group.candidates.build

    # @user = User.where(nickname: @candidate.name)
    # params[:enter][:user_id] = @user
    # params[:enter][:group_id] = @group.id
    # params[:enter][:permission] = true
    # @enter = Enter.create(enter_params)
    #       redirect_to group_path(@group.id)
  end

  def edit; end

  def update
    group.update(group_params)
    redirect_to group_path(group)
  end

  def destroy
    group.destroy
    redirect_to root_path
  end

  def show
    @enter = group.enters.find_by(user: current_user)

    @autor = group.user
    @articles = group.articles
    @events = group.events
  end

  def people
    @users = group.users
  end

  private

  def group
    @group ||= Group.find_by(id: params[:id]) || Group.find(params[:group_id])
  end

  def group_params
    params.require(:group).permit(:name, :context, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div style="background-color: #cff1ef; color: #424874;padding: auto; margin-top:30px;">
	<div class="container">
		<div class="row">
			<div class="col-lg-3" style="margin-top:80px;">All right @
				<br>
				CopyRighr
			</div>
			<div class="col-lg-6">
				<h2>Lorem lorme lorem
				</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
					irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</p>
			</div>
			<div class="col-lg-3" style="margin-top:80px;">
				<%= fa_icon "map-marker-alt" %> scholl@gmail.com
				<br>
				<%= fa_icon "envelope" %> choll@gmail.com
				<br>
				<%= fa_icon "phone" %> +74392347239
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<!-- <nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" style="color: white;">Site</a>
  <form class="form-inline">

    <% if user_signed_in? %>
      <%= link_to new_group_path do %>
          <button type="button" class="btn btn-outline-light"><span>+</span></button>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <button type="button" class="btn btn-outline-warning">Log out</button>
    <%end%>
    <%end%>
    <% else %>
       <%= link_to user_session_path do %>
        <button type="button" class="btn btn-outline-warning">Log in</button>
        <%= link_to new_user_registration_path do %>
         <button type="button" class="btn btn-outline-light btn-sm">Registration</button>

    <%end%>
   <%end%>
   <%end%>
  </form>
</nav> -->
<!-- #e3f2fd; -->
<nav class="navbar navbar-light" style="background-color:  #cff1ef;">
  <a class="navbar-brand" href="/" style="color: #424874;">
    Site
  </a>

  <form class="form-inline">

    <% if user_signed_in? %>
      <div class="btn-group dropleft" >
        <!-- <button type="button" class="btn btn-danger">Action</button> -->
        <button  type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
        </button>
        <%= image_tag(current_user.avatar, width: 40, height: 40) if current_user.avatar.attached? %>
        <div class="dropdown-menu">
        <a class="dropdown-item"> <%= link_to new_group_path do%><p style="padding-left: 20px; color: #000;">Add group</p><%end%></a>
        <a class="dropdown-item"> <%= link_to destroy_user_session_path, method: :delete do%><p style="padding-left: 20px; color: #000;">Logout</p><%end%></a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item"> <%= link_to edit_user_registration_path do%><p style="padding-left: 20px; color: #000;">Settings</p><%end%></a>
      </div>
    </div>

    <% else %>
      <div class="btn-group dropdown" >
        <button type="button" class="btn btn-info">Option</button>
        <button  type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
        <a class="dropdown-item"> <%= link_to user_session_path do%><p style="padding-left: 20px; color: #000;">Login</p><%end%></a>
        <a class="dropdown-item"> <%= link_to new_user_registration_path do%><p style="padding-left: 20px; color: #000;">Registration</p><%end%></a>
      </div>
    </div>


     <!--   <%= link_to user_session_path do %>
        <button type="button" class="btn btn-outline-warning">Login</button>
        <%= link_to new_user_registration_path do %>
         <button type="button" class="btn btn-outline-light btn-sm">Registration</button>

    <%end%>
   <%end%> -->
   <%end%>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %> 
    <div class="container">
       <%= yield %>
    </div>
    <%= render 'layouts/footer' %> 
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello World</h1>